#!/usr/bin/env bash

SUCCESS=false
COUNTER=0

trap 'exit 0' INT

while [ $SUCCESS == false ]; do
    echo
    echo
    echo "==== Running "$*" (Retry count:    $COUNTER) ===="
    COUNTER=$((COUNTER + 1))
    bash -c "$*"
    if [ $? == 0 ]; then
        SUCCESS=true
    else
        # Print the exit code when error occurs
        echo $?
    fi
done
