#!/usr/bin/env bash

SUCCESS=false
COUNTER=0

# Exit if Ctrl + C was pressed
trap 'exit 0' INT

while [ $SUCCESS == false ]; do
    echo
    echo
    COUNTER=$((COUNTER + 1))
    echo "==== Running "$*" (Counts:    $COUNTER) ===="
    bash -c "$*"
    if [ $? == 0 ]; then
        SUCCESS=true
    fi
done
