#!/usr/bin/env bash

SUCCESS=false

# Exit if Ctrl + C was pressed
trap 'exit 0' INT

while [ $SUCCESS == false ]; do
    echo
    echo
    echo "==== Running "$*" ===="
    bash -c "$*"
    if [ $? == 0 ]; then
        SUCCESS=true
    fi
done
